# This is a basic workflow to help you get started with Actions

name: Deploy bicep

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: nfvnet-x6ryeapb2kb7o # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './function'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    environment:
      name: deploy
      url: ${{ steps.fa.outputs.func_url }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: "deploy infra using bicep"
        shell: bash
        run: |
          RGNAME='nfvnet-${{ github.run_number }}'
          az group create -n $RGNAME -l westus2
          az deployment group create \
            --name nfvnet-${{ github.run_number }} \
            --resource-group $RGNAME \
            --template-file IaC/function.bicep \
            --parameters appNameSuffix=${{ github.run_number }}

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: nfvnet-${{ github.run_number }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      
      - name: 'Get Function URL'
        id: fa
        shell: bash
        run: |
          URL=''
          while [ -z "$URL" ]
          do
            echo "trying to get URL"
            URL=$(az functionapp function show \
              --function-name httptrigger1 \
              --name nfvnet-${{ github.run_number }} \
              -g nfvnet-${{ github.run_number }} \
              --query "invokeUrlTemplate" --output tsv)
            echo $URL
          done
          echo "::set-output name=func_url::$URL"

  delete:
    needs: deploy
    runs-on: ubuntu-latest
    environment: delete
    steps:
          # Runs a single command using the runners shell
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "delete all stuff"
        shell: bash
        run: |
          az group delete --yes -n nfvnet-${{ github.run_number }}